### ISSUE TITLE
Add abstracted docker_repo functionality

### ISSUE THREAD

**Issue by jafreck** [Azure/aztk#503]
in addition to `docker_repo`, cluster.yaml should support:
```yaml
toolkit:
  type: spark
  version: 2.2.0
  environment: base/anaconda/miniconda/r
  environment-version: [default]
```

This should be the default.

This toolkit block will map to a docker image tag.
